title: Lamarkdown
description: Command-line markdown compiler for standalone document preparation, based on Python-Markdown.
url: https://lamarkdown.github.io
markdown: kramdown

remote_theme: just-the-docs/just-the-docs@v0.3.3
plugins:
- jekyll-remote-theme

aux_links:
  Github: https://github.com/lamarkdown/lamarkdown
  PyPi: https://pypi.org/project/lamarkdown
  Created and Maintained by David Cooper: https://github.com/davidjacooper/
  
callouts:
  note:
    title: Note
    color: blue
