title: Lamarkdown
description: Command-line markdown compiler for standalone document preparation, based on Python-Markdown
url: https://lamarkdown.github.io
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.3.3
#olivier3lanc/Jekyll-LibDoc 
# pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github:
  repository_url: https://github.com/lamarkdown/lamarkdown
  is_user_page: false
  is_project_page: true
show_downloads: false
