title: Lamarkdown
description: Command-line markdown compiler for standalone document preparation, based on Python-Markdown
url: http://lamarkdown.github.io
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
